### ISSUE TITLE
IndexError: list index out of range,怎么解决，求指点

### ISSUE THREAD

**Issue by lili1234567890** [bamtercelboo/pytorch_Joint-Word-Segmentation-and-POS-Tagging#4]
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main()
  File "main.py", line 74, in main
    train_iter, dev_iter, test_iter, alphabet, alphabet_static = load_data(config=config)
  File "/home/zgy/wll/tibetan_Segand-POS-Tag/DataUtils/mainHelp.py", line 242, in load_data
    train_iter, dev_iter, test_iter, alphabet, alphabet_static = preprocessing(config)
  File "/home/zgy/wll/tibetan_Segand-POS-Tag/DataUtils/mainHelp.py", line 168, in preprocessing
    train_iter, dev_iter, test_iter = create_iter.createIterator()
  File "/home/zgy/wll/tibetan_Segand-POS-Tag/DataUtils/Batch_Iterator.py", line 84, in createIterator
    self._convert_word2id(self.data[id_data], self.operator, self.operator_static)
  File "/home/zgy/wll/tibetan_Segand-POS-Tag/DataUtils/Batch_Iterator.py", line 112, in _convert_word2id
    pos = inst.pos[index]
IndexError: list index out of range

**Comment by dalinvip** [comment]
Hi,
Too little information to see anything, debug carefully by yourself, maybe it is data problem.

Best wishes~
